export const faceRegister = [
  {
    "key": "geibi",
    "first_name": "GEIBI",
    "last_name": "KASSIM",
    "gender": "Male",
    "dob": "1966-07-01",
    "pob": "Nagaf, Iraq",
    "nationality": "Iraqi",
    "wanted_by": "Belgium",
    "wanted_status":1,
    "charge": "Theft with violence and with aggravating circumstances (murder)"
  },
  {
    "key": "ramadan",
    "first_name": "RAMADAN",
    "last_name": "RAMADAN TAHER",
    "gender": "Male",
    "dob": "1987-08-26",
    "pob": "Shikhan, Iraq",
    "nationality": "Iraqi",
    "wanted_by": "Sweden",
    "wanted_status":1,
    "charge": "Murder"
  },
  {
    "key": "qader",
    "first_name": "QADER",
    "last_name": "GARMIAN",
    "gender": "Male",
    "dob": "1997-08-27",
    "pob": "Nagaf, Iraq",
    "nationality": "Iraqi",
    "wanted_by": "Sweden",
    "wanted_status":1,
    "charge": "Kidnapping and murder."
  },
  {
    "key": "alkhazarji",
    "first_name": "NAZAR ABDELKARIM",
    "last_name": "AL KHAZRAJI",
    "gender": "Male",
    "dob": "1985",
    "pob": "Mosul, Iraq",
    "nationality": "Iraqi",
    "wanted_by": "Denmark",
    "wanted_status":1,
    "charge": "War crimes"
  },
  {
    "key": "carl",
    "first_name": "CARL",
    "last_name": "FREER",
    "gender": "Male",
    "dob": "1970",
    "pob": "Sweden",
    "nationality": "Swedish",
    "wanted_by": "None",
    "wanted_status":0,
    "charge": "None"
  },
  {
    "key": "jorge",
    "first_name": "JORGE",
    "last_name": "SEBASTIAO",
    "gender": "Male",
    "dob": "1965",
    "pob": "Portugal",
    "nationality": "Portugese",
    "wanted_by": "None",
    "wanted_status":0,
    "charge": "None"
  },
  {
    "key": "alex",
    "first_name": "ALEX",
    "last_name": "GADOTTI",
    "gender": "Male",
    "dob": "1969",
    "pob": "Italy",
    "nationality": "Italian",
    "wanted_by": "None",
    "wanted_status":0,
    "charge": "None"
  }]
